#!/bin/sh

while true; do

  if [ $docker_remove_containers == "1" ]; then

    echo "Removing stoped docker container's "
    # This prevent all stoped container's from rancher stack being removed
    docker ps -a -f status=exited | grep -v rancher| awk '{if(NR>1) print $1}' | xargs -r docker rm > /dev/null 2>&1

  fi

  if [ $docker_remove_containers == "1" ]; then

    echo "Removing docker images that are not being used"
    docker images -q | xargs docker rmi > /dev/null 2>&1

  fi

  # Sleep
  sleep $docker_loop_interval

done;
